--- #YAML:1.0
name:                WebService-Linode
version:             0.02
abstract:            Perl Interface to the Linode.com API.
license:             perl
author:              
    - Michael Greb <mgreb@linode.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    JSON:                          2
    LWP::UserAgent:                0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
